openapi: 3.0.0
info:
  description: >
    This document specifies an **RESTful API for User Registration** in **WSO2 Identity Server** which can be used to
    perform complete user registration in an API based manner.
  version: 1.0.0
  title: WSO2 Identity Server - User Registration Rest API
  contact:
    name: WSO2
    url: 'https://wso2.com/products/identity-server/'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /registration/initiate:
    post:
      operationId: initiateRegistration
      description: |
        This API provides the capability to initiate a user registration according to the configurations
        of the application.
      requestBody:
        required: true
        description: User registration initiate request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitRegRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegPromptResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegCompleteResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /registration/submit:
    post:
      operationId: submitRegistrationData
      description: This API provides the capability to continue communication of data for an initiated registration
      requestBody:
        required: true
        description: User registration initiate request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRegRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegPromptResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegCompleteResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    InitRegRequest:
      description: |
        The request object to initiate a registration flow configured against the given application id. If the end
        result of the user creation should be aligned with a specific protol, that must be indicated in the initial request.
      required:
        - applicationId
      properties:
        applicationId:
          type: string
          description: |
            The id of the application for which the useer registration is triggered. This will be used to retrieve the configured user registration flow.
          example: 3bd1f207-e5b5-4b45-8a91-13b0acfb2151

    SubmitRegRequest:
      description: |
        The request object that will be communicated to the server as the intermediate steps associated with the
        registration flow. This will contain the user inputs for the attributes requested.
      required:
        - flowId
        - userData
      properties:
        flowId:
          type: string
          description: |
            A unique identifier for the registration flow returned from the server. This identifier will be used to track the continuation of the flow.
          example: d13ec8d2-2d1e-11ee-be56-0242ac120002
        inputs:
          type: object
          description: The parameters required by the registration executor to perform user onboarding.
          additionalProperties:
            type: string
          example:
            username: johnd
            firstname: John
            lastname: Doe

    InputData:
        type: object
        description: The parameters required by the registration executor to perform user onboarding.
        additionalProperties:
          type: string
        example:
          username: johnd
          firstname: John
          lastname: Doe

#    SectionData:
#      type: object
#      description: Contains the data related to a section.
#      required:
#        - id
#        - inputs
#      properties:
#        id:
#          type: string
#          description: The unique identifier of the selected registration executor.
#          example: db1220160cb14f0a8d74b831e0939b62
#        inputs:
#          type: object
#          description: The parameters required by the registration executor to perform user onboarding.
#          additionalProperties:
#            type: string
#          example:
#            username: johnd
#            firstname: John
#            lastname: Doe

    RegPromptResponse:
      type: object
      description: User registration intermediate response body.
      required:
        - flowId
        - flowStatus
        - sections
      properties:
        flowId:
          type: string
          description: |
            A unique identifier for the registration flow returned from the server. This identifier will be used to track the continuation of the flow.
          example: d13ec8d2-2d1e-11ee-be56-0242ac120002
        flowStatus:
          type: string
          enum:
            - INCOMPLETE
            - FAILURE
          description: |
            The status of the registration flow.
            There is a seperate response modal for the COMPLETE state with a registration user assertion that can be
            used for initiating an authentication.
          example: INCOMPLETE
        flowType:
          type: string
          enum:
            - REGISTRATION
          description: The type of the flow. This version only contains flowType REGISTRATION.
          example: REGISTRATION
        prompts:
          description: Array of required elements
          type: array
          items:
            $ref: '#/components/schemas/Prompt'

    RegCompleteResponse:
      type: object
      description: User registration complete response body.
      required:
        - flowId
        - flowStatus
        - userAssertion
        - links
      properties:
        flowId:
          type: string
          description: |
            A unique identifier for the registration flow returned from the server. This identifier will be used to track the continuation of the flow.
          example: d13ec8d2-2d1e-11ee-be56-0242ac120002
        flowStatus:
          type: string
          enum:
            - COMPLETE
          description: |
            The status of the registration flow. This will always be COMPLETE.
          example: COMPLETE
        userAssertion:
          type: string
          description: |
            An assertion for the newly created user based on the authentication protocol to be used for proceeding with the authentication. If the registration is not bound to any protocol, this will be null.

#    Section:
#      type: object
#      properties:
#        id:
#          type: string
#          description: A unique id for the element in the next step array.
#        order:
#          type: integer
#          description: Depicts the order in which the elements should be processed in the array.
#        prompts:
#          type: array
#          description: List of prompts in the section
#          items:
#            $ref: '#/components/schemas/Prompt'

    Prompt:
      type: object
      properties:
        name:
          type: string
          description: The name or identifier of the prompt
          example: firstName
        value:
          type: string
          description: The current value of the prompt (can be pre-filled)
          example: ""
        dataType:
          type: string
          description: Data type of the prompt (e.g., string, number, selection)
          example: string
        isMandatory:
          type: boolean
          description: Indicates if the prompt is required
          example: true
        isReadOnly:
          type: boolean
          description: Indicates if the prompt is read-only
          example: false
        order:
          type: integer
          description: The order in which the prompt appears
          example: 1
        validationRegex:
          type: string
          description: Validation regex for the prompt (if applicable)
          example: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
        i18nKey:
          type: string
          description: Internationalization key for the prompt label
          example: userInfo.firstName
        options:
          type: array
          description: Available options for selection prompts (if applicable)
          items:
            $ref: '#/components/schemas/Option'

    Option:
      type: object
      properties:
        value:
          type: string
          description: The value for the option
          example: password
        i18nKey:
          type: string
          description: Internationalization key for the option label
          example: authMethod.password

    Error:
      type: object
      description: Contains the data related to an error.
      required:
        - code
        - message
        - description
        - traceId
      properties:
        code:
          type: string
          example: ABA-00000
        message:
          type: string
          example: Some error message.
        description:
          type: string
          example: Some error description.
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/pamoda.testing/NestingSampleAPI/1.0.0