openapi: 3.0.0
info:
  description: >
    This document specifies an **RESTful API for User Registration** in **WSO2 Identity Server** which can be used to
    perform complete user registration in an API based manner.
  version: 1.0.0
  title: WSO2 Identity Server - User Registration Rest API
  contact:
    name: WSO2
    url: 'https://wso2.com/products/identity-server/'
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
paths:
  /registration/initiate:
    post:
      operationId: initiateRegistration
      description: |
        This API provides the capability to initiate a user registration according to the configurations
        of the application.
      requestBody:
        required: true
        description: User registration initiate request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitRegRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegPromptResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegCompleteResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /registration/submit:
    post:
      operationId: submitRegistrationData
      description: This API provides the capability to continue communication of data for an initiated registration
      requestBody:
        required: true
        description: User registration initiate request body.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubmitRegRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegPromptResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegCompleteResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    InitRegRequest:
      description: |
        The request object to initiate a registration flow configured against the given application id. If the end
        result of the user creation should be aligned with a specific protol, that must be indicated in the initial request.
      required:
        - applicationId
      properties:
        applicationId:
          type: string
          description: |
          The id of the application for which the useer registration is triggered. This will be used to
          retrieve the configured user registration flow.
          example: 3bd1f207-e5b5-4b45-8a91-13b0acfb2151

    SubmitRegRequest:
      description: |
        The request object that will be communicated to the server as the intermediate steps associated with the
        registration flow. This will contain the user inputs for the attributes requested.
      required:
        - flowId
        - selectedRegistrationExecutor
      properties:
        flowId:
          type: string
          description: |
          A unique identifier for the registration flow returned from the server. This identifier will be used to
          track the continuation of the flow.
          example: d13ec8d2-2d1e-11ee-be56-0242ac120002
        engagedExecutors:
          type: array
          items:
            $ref: '#/components/schemas/SelectedRegExecutor'
          description: Contains the list of registration executors engaged in this step.

    SelectedRegExecutor:
      type: object
      description: Contains the data related to a selected registration executor.
      required:
        - id
      properties:
        id:
          type: string
          description: The unique identifier of the selected registration executor.
          example: db1220160cb14f0a8d74b831e0939b62
        params:
          type: object
          description: The parameters required by the registration executor to perform user onboarding.
          additionalProperties:
            type: string
          example:
            username: johnd
            firstname: John
            lastname: Doe

    RegPromptResponse:
      type: object
      description: User registration intermediate response body.
      required:
        - flowId
        - flowStatus
        - nextStep
        - links
      properties:
        flowId:
          type: string
          description: |
          A unique identifier for the registration flow returned from the server. This identifier will
          be used to track the continuation of the flow.
          example: d13ec8d2-2d1e-11ee-be56-0242ac120002
        flowStatus:
          type: string
          enum:
            - INCOMPLETE
            - FAILURE
          description: |
            The status of the registration flow.
            There is a seperate response modal for the COMPLETE state with a registration user assertion that can be
            used for initiating an authentication.
          example: INCOMPLETE
        flowType:
          type: string
          enum:
            - REGISTRATION
          description: The type of the flow. This version only contains flowType REGISTRATION.
          example: REGISTRATION
        nextStep:
          description: |
          This is an element array where each element contains multiple registration options and all the
          elements in the array should be executed to make the step successful.
          type: array
          items:
            $ref: '#/components/schemas/NextStep'

        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          description: Contains the urls related to the registration flow.

    RegCompleteResponse:
      type: object
      description: User registration complete response body.
      required:
        - flowId
        - flowStatus
        - userAssertion
        - links
      properties:
        flowId:
          type: string
          description: |
          A unique identifier for the registration flow returned from the server. This identifier will be used to
          track the continuation of the flow.
          example: d13ec8d2-2d1e-11ee-be56-0242ac120002
        flowStatus:
          type: string
          enum:
            - COMPLETE
          description: |
            The status of the registration flow. This will always be COMPLETE.
          example: COMPLETE
        userAssertion:
          type: string
          description: |
          An assertion for the newly created user based on the authentication protocol to be used for
          proceeding with the authentication. If the registration is not bound to any protocol, this will be null.
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
          description: Contains the urls related to the registration flow and/or to proceed with the authentication flow.

    NextStep:
      type: object
      properties:
        id:
          type: string
          description: A unique id for the element in the next step array.
        order:
          type: integer
          description: Depictd the order in which the elements should be processed in the array.
        processingMode:
          type: string
          enum:
            - ONE_OF_EXECUTORS
            - ONLY_EXECUTOR
          description: |
            In a single element of the next step, may have one or more registration step executors. This field will
            depict how the executors should be processed.
            - ONE_OF_EXECUTORS - Only one of the executors should be processed.
            - ONLY_EXECUTOR - Only one executor is there and it is mandatory to process.
          example: ONE_OF_EXECUTORS
        registrationExecutors:
          type: array
          items:
            $ref: '#/components/schemas/RegExecutor'
        message:
          $ref: '#/components/schemas/MessageInfo'

    RegExecutor:
      type: object
      description: The details of an executor which perform a specific task of the registration flow.
      properties:
        id:
          type: string
          description: The unique identifier of the registration executor instance.
          example: e54636fe-2f7a-11ee-be56-0242ac120002
        displayName:
          type: string
          description: The display name for the registration executor.
          example: Attribute Collector
        type:
          type: string
          description: The type of the registration executor.
          example: Credential
        order:
          type: integer
          description: The order in which the registration executor should be engaged.
          example: 1
        metadata:
          $ref: '#/components/schemas/RegExecutorMetadata'
        message:
          $ref: '#/components/schemas/MessageInfo'

    RegExecutorMetadata:
      type: object
      description: Contains the metadata related to a registration executor.
      required:
        - i18nKey
      properties:
        i18nKey:
          type: string
          description: |
          The i18n key for the registration executor. This can be used to get the localized text for the registration
          executor.
        promptType:
          type: string
          enum:
            - USER_PROMPT
            - INTERNAL_PROMPT
            - REDIRECTION_PROMPT
          description: |
            The type of the prompt. The prompt can be one of the following.
            - USER_PROMPT - The prompt is for the user to input the required parameters for the registration.
            - INTERNAL_PROMPT - The prompt is for the system to perform an internal action which will result in
              obtaining the required parameters
            - REDIRECTION_PROMPT - The prompt is for the user to be redirected to a different url which will result
            in obtaining the required parameters.
            ex: Register using a social authenticator which requires the user to be redirect to the federation
            identity provider. In this case, other required data will be available in `additionalData`.
          example: USER_PROMPT
        attributes:
          type: array
          items:
            $ref: '#/components/schemas/AttributeInfo'
          description: Contains the user attributes required by the registration executor.
        credentials:
          type: array
          items:
            $ref: '#/components/schemas/CredentialInfo'
          description: Contains the credentials required by the registration executor.
        additionalData:
          type: object
          additionalProperties:
            type: string
          description: |
            Contains any additional data related to the authenticator which would be needed for the application to perform
            authentication. ex: Fido2 challenge, redirectUrl for federated authentication.
          example:
            redirectUrl: https://accounts.google.com/o/oauth2/auth?response_type=code&redirect_uri=https%3A%2F%2Fexample-app.com%2Fredirect&state=e12f-ed27-49e5-ad0a-8bbb5671d81e%2COIDC&client_id=231644702133-ds23592jt.apps.googleusercontent.com&scope=openid

    AttributeInfo:
      type: object
      description: The user attribute information required by the registration executor to perform the registration.
      required:
        - name
        - dataType
        - order
        - i18nKey
      properties:
        name:
          type: string
          description: The display name of the attribute.
          example: username
        value:
          type: string
          description: The value of the attribute if already available.
          example: johndoe
        dataType:
          type: string
          enum:
            - STRING
            - NUMBER
            - BOOLEAN
            - DATE
          description: Indicates the data type of the parameter.
          example: STRING
        isMandatory:
          type: boolean
          description: Indicates whether the attribute is mandatory to be filled.
          example: true
        isReadOnly:
          type: boolean
          description: Indicates whether the attribute is read only if a value is already available.
          example: true
        order:
          type: integer
          description: Indicates the display order of the attribute.
          example: 1
        validationRegex:
          type: string
          description: Contains the regex pattern to validate the value of the attribute.
          example: ^[\S]{3,50}$
        i18nKey:
          type: string
          description: The i18n key for the attribute. This can be used to get the localized text for the attribute.
          example: attribute.username

    CredentialInfo:
      type: object
      description: |
      Credential information required by the registration executor to perform the registration. This can be a
      password, OTP, etc and it is mandatory.
      required:
        - name
        - dataType
        - order
        - i18nKey
      properties:
        name:
          type: string
          description: The display name of the credential.
          example: password
        dataType:
          type: string
          enum:
            - STRING
            - OTP
          description: Indicates the data type of the credential.
          example: STRING
        order:
          type: integer
          description: Indicates the display order of the attribute.
          example: 1
        validationRegex:
          type: string
          description: Contains the regex pattern to validate the value of the credential.
          example: ^[\S]{3,50}$
        i18nKey:
          type: string
          description: The i18n key for the credential name. This can be used to get the localized text.
          example: credential.password

    MessageInfo:
      type: object
      description: Contains the message information related to the registration step element.
      required:
        - type
        - content
        - context
        - i18nKey
      properties:
        type:
          type: string
          enum:
            - INFO
            - ERROR
          description: Indicates the type of the message.
          example: INFO
        content:
          type: string
          description: The actual message body.
          example: A verification code is sent to the provided email.
        context:
          type: array
          items:
            $ref: '#/components/schemas/Context'
        i18nKey:
          type: string
          description: The i18n key for the message. This can be used to get the localized text for the message.
          example: info.sent.email.otp

    Context:
      type: object
      description: |
        Contains any context information related to the message. The context information can be used to create localized
        messages. The available different context information is bound to the messageId.
        ex - mobile number that the OTP is sent.
      required:
        - key
        - value
      properties:
        key:
          type: string
          example: providedEmail
        value:
          type: string
          example: 'pa******@gmail.com'

    Link:
      type: object
      description: Contains the data related to a link.
      required:
        - name
        - href
        - method
      properties:
        name:
          type: string
          description: The identifier of the link.
          example: registration
        href:
          type: string
          description: The relative url of the link.
          example: /api/registration/v1
        method:
          type: string
          enum:
            - GET
            - POST
          description: The supported http methods of the link.
          example: POST

    Error:
      type: object
      description: Contains the data related to an error.
      required:
        - code
        - message
        - description
        - traceId
      properties:
        code:
          type: string
          example: ABA-00000
        message:
          type: string
          example: Some error message.
        description:
          type: string
          example: Some error description.
        traceId:
          type: string
          example: e0fbcfeb-3617-43c4-8dd0-7b7d38e13047